### ISSUE TITLE
获取广告计划接口 AdGetV2Api 不支持批量？

### ISSUE THREAD

**Issue by Sun-Xingbin** [oceanengine/ad_open_sdk_java#1]
https://open.oceanengine.com/labels/7/docs/1696710535150604
官网文档返回的数据中包括分页信息 page_info，以及广告列表 data.list

AdGetV2Response 返回的数据中只有一个 AdGetV2ResponseData 对象，里面只包含一个广告对象。

如何批量查询广告计划？

**Comment by erupts** [comment]
使用最新的1.1.3版本也发现有这个问题，传递了分页对象，但是返回的只有单条数据
